export enum Events {
	onFetched = 'onFetched',
	onConverted = 'onConverted',
	onSelected = 'onSelected',
	onAddClicked = 'onAddClicked',
	onSearch = 'onSearch',
	onScroll = 'onScroll',
	onLoadMore = 'onLoadMore',
	onScrollDelayed = 'onScrollDelayed',
	onCancelClicked = 'onCancelClicked',
	onOutsideClicked = 'onOutsideClicked',
	onModelValueUpdate = 'update:modelValue',
	onSaveClicked = 'onSaveClicked',
	onDeleteClicked = 'onDeleteClicked',
	onContinueClicked = 'onContinueClicked',
	onClick = 'onClick',
	onDismissClicked = 'onDismissClicked',
	click = 'click',
	change = 'change',
	blur = 'blur',
}
