// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonDropdown: typeof import('./src/components/button/dropdown/ButtonDropdown.vue')['default']
    Configurations: typeof import('./src/components/configurations/Configurations.vue')['default']
    Dialog: typeof import('./src/components/dialog/Dialog.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    FooterButton: typeof import('./src/components/button/footer/FooterButton.vue')['default']
    IconifyFaFacebookF: typeof import('~icons/fa/facebook-f')['default']
    IconifyFaInstagram: typeof import('~icons/fa/instagram')['default']
    IconifyFaLinkedin: typeof import('~icons/fa/linkedin')['default']
    IconifyFaYoutubePlay: typeof import('~icons/fa/youtube-play')['default']
    IconifyIcBaselineDarkMode: typeof import('~icons/ic/baseline-dark-mode')['default']
    IconifyLineMdHeartFilled: typeof import('~icons/line-md/heart-filled')['default']
    IconifyLineMdLightbulbFilled: typeof import('~icons/line-md/lightbulb-filled')['default']
    IconifyLineMdMoonFilledAltLoop: typeof import('~icons/line-md/moon-filled-alt-loop')['default']
    IconifyMdiClose: typeof import('~icons/mdi/close')['default']
    LocaleSelector: typeof import('./src/components/locale/selector/LocaleSelector.vue')['default']
    NavigationBar: typeof import('./src/components/navigation/bar/NavigationBar.vue')['default']
    NavigationBarMenuButtons: typeof import('./src/components/navigation/bar/menu/buttons/NavigationBarMenuButtons.vue')['default']
    NavigationBarMenuButtonsButton: typeof import('./src/components/navigation/bar/menu/buttons/button/NavigationBarMenuButtonsButton.vue')['default']
    NavigationMenuList: typeof import('./src/components/navigation/bar/menu/list/NavigationMenuList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideDialog: typeof import('./src/components/dialog/SideDialog.vue')['default']
    ThemeIcon: typeof import('./src/components/theme/ThemeIcon.vue')['default']
    ThemeSelector: typeof import('./src/components/theme/selector/ThemeSelector.vue')['default']
    ThemeSelectorSelect: typeof import('./src/components/theme/selector/ThemeSelectorSelect.vue')['default']
    ThemeSelectorSwitch: typeof import('./src/components/theme/selector/ThemeSelectorSwitch.vue')['default']
  }
}
